INSERT INTO cities (country_code, slug, timezone)
SELECT 'MD', seed.slug, 'Europe/Chisinau'
FROM (
	VALUES
		('anenii-noi'),
		('balti'),
		('briceni'),
		('cahul'),
		('calarasi'),
		('cantemir'),
		('causeni'),
		('ceadir-lunga'),
		('chisinau'),
		('cimislia'),
		('comrat'),
		('congaz'),
		('cosnita'),
		('criuleni'),
		('donduseni'),
		('drochia'),
		('edinet'),
		('falesti'),
		('floresti'),
		('glodeni'),
		('hincesti'),
		('ialoveni'),
		('leova'),
		('nisporeni'),
		('ocnita'),
		('orhei'),
		('otaci'),
		('rezina'),
		('riscani'),
		('singerei'),
		('soldanesti'),
		('soroca'),
		('stefan-voda'),
		('straseni'),
		('taraclia'),
		('telenesti'),
		('ungheni'),
		('varnita'),
		('vulcanesti')
) AS seed(slug)
ON CONFLICT (country_code, slug) DO UPDATE SET
	timezone = EXCLUDED.timezone,
	active = TRUE;

INSERT INTO city_translations (country_code, city_slug, locale_code, name)
SELECT 'MD',
	seed.slug,
	locale.code,
	CASE locale.code WHEN 'ru' THEN seed.ru_name ELSE seed.name END
FROM (
	VALUES
		('anenii-noi', 'Anenii Noi', 'Новые Анены'),
		('balti', 'Bălți', 'Бельцы'),
		('briceni', 'Briceni', 'Бричаны'),
		('cahul', 'Cahul', 'Кагул'),
		('calarasi', 'Călărași', 'Калараш'),
		('cantemir', 'Cantemir', 'Кантемир'),
		('causeni', 'Căușeni', 'Каушаны'),
		('ceadir-lunga', 'Ceadîr-Lunga', 'Чадыр-Лунга'),
		('chisinau', 'Chișinău', 'Кишинёв'),
		('cimislia', 'Cimișlia', 'Чимишлия'),
		('comrat', 'Comrat', 'Комрат'),
		('congaz', 'Congaz', 'Конгаз'),
		('cosnita', 'Coșnița', 'Кошница'),
		('criuleni', 'Criuleni', 'Криуляны'),
		('donduseni', 'Dondușeni', 'Дондюшаны'),
		('drochia', 'Drochia', 'Дрокия'),
		('edinet', 'Edineț', 'Единцы'),
		('falesti', 'Fălești', 'Фалешты'),
		('floresti', 'Florești', 'Флорешты'),
		('glodeni', 'Glodeni', 'Глодяны'),
		('hincesti', 'Hîncești', 'Хынчешты'),
		('ialoveni', 'Ialoveni', 'Яловены'),
		('leova', 'Leova', 'Леова'),
		('nisporeni', 'Nisporeni', 'Ниспорены'),
		('ocnita', 'Ocnița', 'Окница'),
		('orhei', 'Orhei', 'Оргеев'),
		('otaci', 'Otaci', 'Отачь'),
		('rezina', 'Rezina', 'Резина'),
		('riscani', 'Rîșcani', 'Рышканы'),
		('singerei', 'Sîngerei', 'Сынжерей'),
		('soldanesti', 'Șoldănești', 'Шолданешты'),
		('soroca', 'Soroca', 'Сороки'),
		('stefan-voda', 'Ștefan Vodă', 'Штефан-Водэ'),
		('straseni', 'Strășeni', 'Страшены'),
		('taraclia', 'Taraclia', 'Тараклия'),
		('telenesti', 'Telenești', 'Теленешты'),
		('ungheni', 'Ungheni', 'Унгены'),
		('varnita', 'Varnița', 'Варница'),
		('vulcanesti', 'Vulcănești', 'Вулканешты')
) AS seed(slug, name, ru_name)
CROSS JOIN locales locale
WHERE locale.code IN ('en', 'ro', 'ru')
ON CONFLICT (country_code, city_slug, locale_code) DO UPDATE SET
	name = EXCLUDED.name;

INSERT INTO institutions (country_code, slug, name, institution_type, website_url)
VALUES
	('MD', 'moldindconbank', 'Moldindconbank', 'BANK', 'https://micb.md'),
	('MD', 'fincombank', 'FinComBank', 'BANK', 'https://fincombank.com'),
	('MD', 'energbank', 'Energbank', 'BANK', 'https://www.energbank.com'),
	('MD', 'eurocreditbank', 'EuroCreditBank', 'BANK', 'https://www.ecb.md'),
	('MD', 'comertbank', 'COMERȚBANK', 'BANK', 'https://comertbank.md'),
	('MD', 'procreditbank-md', 'ProCredit Bank Moldova', 'BANK', 'https://www.procreditbank.md')
ON CONFLICT (country_code, slug) DO UPDATE SET
	name = EXCLUDED.name,
	institution_type = EXCLUDED.institution_type,
	website_url = EXCLUDED.website_url,
	active = TRUE;

INSERT INTO locations (institution_id, country_code, city_slug, slug, name, address, phone, email)
SELECT institution.id, 'MD', seed.city_slug, seed.slug, seed.name, seed.address, seed.phone, seed.email
FROM (
	VALUES
		('moldindconbank', 'chisinau', 'micb-centru-chisinau', 'Moldindconbank Sucursala Centru', 'mun. Chișinău, str. Armenească, 38', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'chisinau', 'micb-telecomtrans-chisinau', 'Moldindconbank Sucursala Telecomtrans', 'mun. Chișinău, str. A. Șciusev, 76/A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'chisinau', 'micb-invest-chisinau', 'Moldindconbank Sucursala Invest', 'mun. Chișinău, bd. Moscova, 14/1', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'chisinau', 'micb-remiz-chisinau', 'Moldindconbank Sucursala Remiz', 'mun. Chișinău, bd. Mircea cel Bătrîn, 30', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'chisinau', 'micb-telecentru-chisinau', 'Moldindconbank Sucursala Telecentru', 'mun. Chișinău, șos. Hîncești, 53', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'balti', 'micb-31-august-balti', 'Moldindconbank Sucursala Bălți', 'mun. Bălți, str. 31 August 1989, 20/A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'drochia', 'micb-independentei-drochia', 'Moldindconbank Sucursala Drochia', 'or. Drochia, bd. Independenței, 28/61', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'orhei', 'micb-vasile-lupu-orhei', 'Moldindconbank Sucursala Orhei', 'mun. Orhei, str. Vasile Lupu, 38/A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'rezina', 'micb-27-august-rezina', 'Moldindconbank Sucursala Rezina', 'or. Rezina, str. 27 August, 48/A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'donduseni', 'micb-serghei-lazo-donduseni', 'Moldindconbank Sucursala Dondușeni', 'or. Dondușeni, str. Serghei Lazo, 14', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'edinet', 'micb-independentei-edinet', 'Moldindconbank Sucursala Edineț', 'mun. Edineț, str. Independenței, 104', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'soroca', 'micb-stefan-soroca', 'Moldindconbank Sucursala Soroca', 'mun. Soroca, str. Ștefan cel Mare, 22/A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'straseni', 'micb-stefan-straseni', 'Moldindconbank Sucursala Strășeni', 'mun. Strășeni, str. Ștefan cel Mare, 125', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'cantemir', 'micb-stefan-voda-cantemir', 'Moldindconbank Sucursala Cantemir', 'or. Cantemir, str. Ștefan Vodă, 18/B', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'hincesti', 'micb-mihalcea-hincu-hincesti', 'Moldindconbank Sucursala Hîncești', 'mun. Hîncești, str. Mihalcea Hîncu, 125', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'briceni', 'micb-independentei-briceni', 'Moldindconbank Sucursala Briceni', 'or. Briceni, str. Independenței, 36', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'floresti', 'micb-31-august-floresti', 'Moldindconbank Sucursala Florești', 'or. Florești, str. 31 August 1989, 10', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'causeni', 'micb-mateevici-causeni', 'Moldindconbank Sucursala Căușeni', 'or. Căușeni, str. Mateevici Alexei, 7/A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'ungheni', 'micb-nationala-ungheni', 'Moldindconbank Sucursala Ungheni', 'mun. Ungheni, str. Națională, 17', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'telenesti', 'micb-dacia-telenesti', 'Moldindconbank Sucursala Telenești', 'or. Telenești, str. Dacia, 3', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'cahul', 'micb-republicii-cahul', 'Moldindconbank Sucursala Cahul', 'mun. Cahul, str. Prospectului Republicii, 17A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'comrat', 'micb-pobedi-comrat', 'Moldindconbank Sucursala Comrat', 'mun. Comrat, str. Pobedî, 50', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'ceadir-lunga', 'micb-lenin-ceadir-lunga', 'Moldindconbank Sucursala Ceadîr-Lunga', 'mun. Ceadîr-Lunga, str. Lenin, 50/1', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'falesti', 'micb-eminescu-falesti', 'Moldindconbank Sucursala Fălești', 'or. Fălești, str. Mihai Eminescu, 16/A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'glodeni', 'micb-suveranitatii-glodeni', 'Moldindconbank Sucursala Glodeni', 'or. Glodeni, str. Suveranității, 17', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'nisporeni', 'micb-suveranitatii-nisporeni', 'Moldindconbank Sucursala Nisporeni', 'or. Nisporeni, str. Suveranității, 10/A', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'riscani', 'micb-independentei-riscani', 'Moldindconbank Sucursala Rîșcani', 'or. Rîșcani, str. Independenței, 14/C', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'soldanesti', 'micb-pacii-soldanesti', 'Moldindconbank Sucursala Șoldănești', 'or. Șoldănești, str. Păcii, 1', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'ocnita', 'micb-biruintei-ocnita', 'Moldindconbank Sucursala Ocnița', 'or. Ocnița, str. 50 Ani ai Biruinței, 19', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'stefan-voda', 'micb-31-august-stefan-voda', 'Moldindconbank Sucursala Ștefan Vodă', 'or. Ștefan Vodă, str. 31 August 1989, 7', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'otaci', 'micb-prieteniei-otaci', 'Moldindconbank Agenția Otaci', 'or. Otaci, str. Prieteniei, 97', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'cosnita', 'micb-cosnita', 'Moldindconbank Sucursala Coșnița', 's. Coșnița, raionul Dubăsari', '022 71 71 71', 'info@micb.md'),
		('moldindconbank', 'varnita', 'micb-tighina-varnita', 'Moldindconbank Agenția Varnița', 's. Varnița, str. Tighina, 111', '022 71 71 71', 'info@micb.md'),
		('fincombank', 'ceadir-lunga', 'fincombank-lomonosov-ceadir-lunga', 'FinComBank Agenția Ceadîr-Lunga', 'UTA Găgăuzia, mun. Ceadîr-Lunga, str. Lomonosov, 10', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'comrat', 'fincombank-pobeda-comrat', 'FinComBank Sucursala Comrat', 'UTA Găgăuzia, mun. Comrat, str. Pobeda, 115', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'congaz', 'fincombank-lenin-congaz', 'FinComBank Agenția Congaz', 'UTA Găgăuzia, s. Congaz, str. Lenin, 51/4', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'balti', 'fincombank-bulgara-balti', 'FinComBank Agenția Bulgara Bălți', 'mun. Bălți, str. Bulgară, 120A', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'balti', 'fincombank-iorga-balti', 'FinComBank Agenția N. Iorga Bălți', 'mun. Bălți, str. N. Iorga, 11/3', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'balti', 'fincombank-stefan-73-balti', 'FinComBank Sucursala Bălți', 'mun. Bălți, str. Ștefan cel Mare, 73', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'cahul', 'fincombank-republicii-cahul', 'FinComBank Sucursala Cahul', 'mun. Cahul, str. Republicii, 20A', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-dacia-20-chisinau', 'FinComBank Dacia 20', 'mun. Chișinău, bd. Dacia, 20', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-arborilor-17-chisinau', 'FinComBank Arborilor 17/1', 'mun. Chișinău, str. Arborilor, 17/1', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-decebal-139-chisinau', 'FinComBank Decebal 139', 'mun. Chișinău, str. Decebal, 139', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-creanga-74-chisinau', 'FinComBank I. Creangă 74', 'mun. Chișinău, str. I. Creangă, 74', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-stefan-6-chisinau', 'FinComBank Ștefan cel Mare 6', 'mun. Chișinău, bd. Ștefan cel Mare, 6', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-hincesti-60-chisinau', 'FinComBank Hîncești 60/4', 'mun. Chișinău, str. Hîncești, 60/4', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-puskin-26-chisinau', 'FinComBank Central Office', 'mun. Chișinău, str. A. Pușkin, 26', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-mircea-10-chisinau', 'FinComBank Mircea cel Bătrîn 10', 'mun. Chișinău, bd. Mircea cel Bătrîn, 10', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'chisinau', 'fincombank-moscovei-9-chisinau', 'FinComBank Moscovei 9', 'mun. Chișinău, bd. Moscovei, 9', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'edinet', 'fincombank-independentei-edinet', 'FinComBank Sucursala Edineț', 'mun. Edineț, str. Independenței, 112', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'hincesti', 'fincombank-31-august-hincesti', 'FinComBank Sucursala Hîncești', 'mun. Hîncești, str. 31 August, 5', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'hincesti', 'fincombank-chisinaului-hincesti', 'FinComBank Agenția Hîncești', 'mun. Hîncești, str. Chișinăului, 8, of. 2', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'orhei', 'fincombank-eminescu-orhei', 'FinComBank Sucursala Orhei', 'mun. Orhei, str. M. Eminescu, 1', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'soroca', 'fincombank-alexandru-cel-bun-soroca', 'FinComBank Sucursala Soroca', 'mun. Soroca, str. Alexandru cel Bun, 24', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'straseni', 'fincombank-eminescu-straseni', 'FinComBank Agenția Strășeni', 'mun. Strășeni, str. M. Eminescu, 33', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'ungheni', 'fincombank-bernardazzi-ungheni', 'FinComBank Agenția Bernardazzi Ungheni', 'mun. Ungheni, str. A. Bernardazzi, 7', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'ungheni', 'fincombank-nationala-ungheni', 'FinComBank Sucursala Ungheni', 'mun. Ungheni, str. Națională, 25', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'anenii-noi', 'fincombank-tighina-anenii-noi', 'FinComBank Agenția Anenii Noi', 'or. Anenii Noi, str. Tighina, 2', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'briceni', 'fincombank-prieteniei-briceni', 'FinComBank Agenția Briceni', 'or. Briceni, str. Prieteniei, 4', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'calarasi', 'fincombank-eminescu-calarasi', 'FinComBank Agenția Călărași', 'or. Călărași, str. M. Eminescu, 21', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'causeni', 'fincombank-eminescu-causeni', 'FinComBank Sucursala Căușeni', 'or. Căușeni, str. M. Eminescu, 16', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'cimislia', 'fincombank-stefan-cimislia', 'FinComBank Agenția Cimișlia', 'or. Cimișlia, str. Ștefan cel Mare, 19', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'drochia', 'fincombank-31-august-18-drochia', 'FinComBank Agenția Drochia 31 August', 'or. Drochia, str. 31 August 1989, 18A', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'drochia', 'fincombank-independentei-drochia', 'FinComBank Sucursala Drochia', 'or. Drochia, str. Independenței, 28/63', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'falesti', 'fincombank-eminescu-falesti', 'FinComBank Agenția Fălești', 'or. Fălești, str. M. Eminescu, 1B', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'floresti', 'fincombank-31-august-floresti', 'FinComBank Sucursala Florești', 'or. Florești, str. 31 August, 27', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'glodeni', 'fincombank-suveranitatii-glodeni', 'FinComBank Agenția Glodeni', 'or. Glodeni, str. Suveranității, 8', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'ialoveni', 'fincombank-alexandru-cel-bun-ialoveni', 'FinComBank Agenția Ialoveni', 'or. Ialoveni, str. Alexandru cel Bun, 43A', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'nisporeni', 'fincombank-suveranitatii-15-nisporeni', 'FinComBank Agenția Nisporeni 15/2', 'or. Nisporeni, str. Suveranității, 15/2', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'nisporeni', 'fincombank-suveranitatii-3-nisporeni', 'FinComBank Agenția Nisporeni 3', 'or. Nisporeni, str. Suveranității, 3', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'rezina', 'fincombank-27-august-rezina', 'FinComBank Agenția Rezina', 'or. Rezina, str. 27 August, 44A', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'riscani', 'fincombank-independentei-riscani', 'FinComBank Sucursala Rîșcani', 'or. Rîșcani, str. Independenței, 13, of. 3', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'singerei', 'fincombank-independentei-singerei', 'FinComBank Agenția Sîngerei', 'or. Sîngerei, str. Independenței, 123/B', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'stefan-voda', 'fincombank-31-august-stefan-voda', 'FinComBank Agenția Ștefan Vodă', 'or. Ștefan Vodă, str. 31 August 1989, 3', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'taraclia', 'fincombank-lenin-taraclia', 'FinComBank Agenția Lenin Taraclia', 'or. Taraclia, str. Lenin, 143/9', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'taraclia', 'fincombank-stefan-taraclia', 'FinComBank Agenția Ștefan cel Mare Taraclia', 'or. Taraclia, str. Ștefan cel Mare, 57', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'telenesti', 'fincombank-dacia-telenesti', 'FinComBank Agenția Telenești', 'or. Telenești, str. Dacia, 7', '022 269 999', 'fincom@fincombank.com'),
		('fincombank', 'vulcanesti', 'fincombank-frunze-vulcanesti', 'FinComBank Agenția Vulcănești', 'or. Vulcănești, str. Frunze, 1', '022 269 999', 'fincom@fincombank.com'),
		('energbank', 'chisinau', 'energbank-central-chisinau', 'Energbank Oficiul Central', 'mun. Chișinău, str. Tighina, 23/3', '022 858 030', 'office@energbank.com'),
		('energbank', 'chisinau', 'energbank-centru-chisinau', 'Energbank Sucursala Centru', 'mun. Chișinău, str. Mihai Eminescu, 74, D102', '022 858 073', 'office@energbank.com'),
		('energbank', 'chisinau', 'energbank-botanica-chisinau', 'Energbank Sucursala Botanica', 'mun. Chișinău, bd. Decebal, 91', '022 853 792', 'office@energbank.com'),
		('energbank', 'chisinau', 'energbank-ciocana-chisinau', 'Energbank Sucursala Ciocana', 'mun. Chișinău, str. Mircea cel Bătrân, 4/4', '022 408 287', 'office@energbank.com'),
		('energbank', 'chisinau', 'energbank-riscani-chisinau', 'Energbank Sucursala Rîșcani', 'mun. Chișinău, bd. Moscova, 5', '022 430 910', 'office@energbank.com'),
		('energbank', 'balti', 'energbank-stefan-balti', 'Energbank Sucursala Bălți', 'mun. Bălți, str. Ștefan cel Mare, 6/3', '0231 88 039', 'office@energbank.com'),
		('energbank', 'falesti', 'energbank-eminescu-falesti', 'Energbank Agenția Fălești', 'or. Fălești, str. Mihai Eminescu, 3', '0259 80 091', 'office@energbank.com'),
		('energbank', 'ungheni', 'energbank-nationala-ungheni', 'Energbank Agenția Ungheni', 'mun. Ungheni, str. Națională, 27', '0236 80 992', 'office@energbank.com'),
		('energbank', 'donduseni', 'energbank-lazo-donduseni', 'Energbank Sucursala Dondușeni', 'or. Dondușeni, str. S. Lazo, 16', '0251 21 300', 'office@energbank.com'),
		('energbank', 'drochia', 'energbank-31-august-drochia', 'Energbank Sucursala Drochia', 'or. Drochia, str. 31 August, 33', '0252 27 876', 'office@energbank.com'),
		('energbank', 'edinet', 'energbank-independentei-edinet', 'Energbank Sucursala Edineț', 'mun. Edineț, str. Independenței, 106', '0246 25 383', 'office@energbank.com'),
		('energbank', 'ocnita', 'energbank-biruintei-ocnita', 'Energbank Sucursala Ocnița', 'or. Ocnița, str. 50 ani ai Biruinței, 19/B', '0271 68 007', 'office@energbank.com'),
		('energbank', 'hincesti', 'energbank-chisinaului-hincesti', 'Energbank Sucursala Hîncești', 'mun. Hîncești, str. Chișinăului, 10', '0269 80 062', 'office@energbank.com'),
		('energbank', 'anenii-noi', 'energbank-concilierii-anenii-noi', 'Energbank Sucursala Anenii Noi', 'or. Anenii Noi, str. Concilierii Naționale, 2A', '0265 21 214', 'office@energbank.com'),
		('energbank', 'orhei', 'energbank-vasile-lupu-orhei', 'Energbank Sucursala Orhei', 'mun. Orhei, str. Vasile Lupu, 34/5', '0235 27 461', 'office@energbank.com'),
		('energbank', 'cahul', 'energbank-stefan-cahul', 'Energbank Sucursala Cahul', 'mun. Cahul, str. Ștefan cel Mare, 20B', '0299 80 060', 'office@energbank.com'),
		('energbank', 'comrat', 'energbank-biruintei-comrat', 'Energbank Sucursala Comrat', 'mun. Comrat, str. Biruinței, 47', '0298 80 061', 'office@energbank.com'),
		('energbank', 'leova', 'energbank-stefan-leova', 'Energbank Sucursala Leova', 'or. Leova, str. Ștefan cel Mare, 50', '0263 22 877', 'office@energbank.com'),
		('comertbank', 'chisinau', 'comertbank-kiev-chisinau', 'COMERȚBANK Sucursala nr. 1', 'mun. Chișinău, str. Kiev, 16/1', '022 835 774', 'cards@comertbank.md'),
		('comertbank', 'cahul', 'comertbank-31-august-cahul', 'COMERȚBANK Agenția nr. 4 Cahul', 'or. Cahul, str. 31 August, 4D nr. 2', '0299 800 20', 'cards@comertbank.md'),
		('comertbank', 'balti', 'comertbank-stefan-balti', 'COMERȚBANK Sucursala nr. 2', 'mun. Bălți, str. Ștefan cel Mare, 73', '0231 800 25', 'cards@comertbank.md'),
		('comertbank', 'chisinau', 'comertbank-ismail-chisinau', 'COMERȚBANK Sucursala nr. 3', 'mun. Chișinău, str. Ismail, 98/4', '022 835 830', 'cards@comertbank.md'),
		('comertbank', 'chisinau', 'comertbank-creanga-chisinau', 'COMERȚBANK Agenția nr. 1', 'mun. Chișinău, str. Ion Creangă, 49/5', '022 835 763', 'cards@comertbank.md'),
		('comertbank', 'chisinau', 'comertbank-decebal-chisinau', 'COMERȚBANK Agenția nr. 3', 'mun. Chișinău, str. Decebal, 99', '022 835 892', 'cards@comertbank.md'),
		('comertbank', 'chisinau', 'comertbank-stefan-chisinau', 'COMERȚBANK Agenția nr. 4', 'mun. Chișinău, bd. Ștefan cel Mare și Sfânt, 126', '022 836 761', 'cards@comertbank.md'),
		('procreditbank-md', 'chisinau', 'procredit-head-office-chisinau', 'ProCredit Bank Head Office', 'mun. Chișinău, bd. Ștefan cel Mare și Sfânt, 65, of. 901', '+373 22 27 07 07', 'mda.office@procredit-group.com'),
		('procreditbank-md', 'chisinau', 'procredit-vlaicu-parcalab-chisinau', 'ProCredit Bank Sucursala nr. 2', 'mun. Chișinău, str. Vlaicu Pârcălab, 63', '+373 22 27 07 07', 'mda.office@procredit-group.com'),
		('procreditbank-md', 'chisinau', 'procredit-renasterii-chisinau', 'ProCredit Bank Agenția Renașterii', 'mun. Chișinău, bd. Renașterii Naționale, 12', '+373 22 27 07 07', 'mda.office@procredit-group.com'),
		('procreditbank-md', 'chisinau', 'procredit-dacia-chisinau', 'ProCredit Bank Agenția Dacia', 'mun. Chișinău, bd. Dacia, 24/2', '+373 22 27 07 07', 'mda.office@procredit-group.com'),
		('eurocreditbank', 'chisinau', 'eurocreditbank-ismail-chisinau', 'EuroCreditBank Filiala nr. 001', 'mun. Chișinău, str. Ismail, 33', '+373 22 500 200', 'office@eurocreditbank.md'),
		('eurocreditbank', 'chisinau', 'eurocreditbank-mircea-chisinau', 'EuroCreditBank Agenția nr. 003', 'mun. Chișinău, str. Mircea cel Bătrîn, 32/10', '+373 22 500 200', 'office@eurocreditbank.md')
) AS seed(institution_slug, city_slug, slug, name, address, phone, email)
JOIN institutions institution ON institution.country_code = 'MD' AND institution.slug = seed.institution_slug
ON CONFLICT (country_code, city_slug, slug) DO UPDATE SET
	name = EXCLUDED.name,
	address = EXCLUDED.address,
	phone = EXCLUDED.phone,
	email = EXCLUDED.email,
	active = TRUE;

INSERT INTO rate_sources (institution_id, country_code, slug, source_type, parser_key, source_url, refresh_interval_minutes, config_json)
SELECT institution.id, 'MD', seed.slug, 'MARKET_HTML', seed.parser_key, seed.source_url, 60, seed.config_json::JSONB
FROM (
	VALUES
		('moldindconbank-md-cash', 'moldindconbank', 'micb-html', 'https://micb.md/', '{"rateType":"CASH"}'),
		('fincombank-md-cash', 'fincombank', 'fincombank-html', 'https://fincombank.com/ro/curs-valutar', '{"rateType":"CASH"}'),
		('comertbank-md-cash', 'comertbank', 'comertbank-html', 'https://comertbank.md/contacts/vault.php', '{"rateType":"CASH"}'),
		('eurocreditbank-md-cash', 'eurocreditbank', 'eurocreditbank-html',
			'https://www.eurocreditbank.md/en/sucursala_1_chisinau/', '{"rateType":"CASH"}')
) AS seed(slug, institution_slug, parser_key, source_url, config_json)
JOIN institutions institution ON institution.country_code = 'MD' AND institution.slug = seed.institution_slug
ON CONFLICT (slug) DO UPDATE SET
	source_url = EXCLUDED.source_url,
	parser_key = EXCLUDED.parser_key,
	refresh_interval_minutes = EXCLUDED.refresh_interval_minutes,
	config_json = EXCLUDED.config_json,
	enabled = TRUE;
